#############################################################################
# Makefile for building: tieba
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 8? 25 04:02:09 2026
# Project:  tieba.pro
# Template: app
# Command: c:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile tieba.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DTIEBA_HAS_DBUS -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wno-psabi -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSql -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDBus -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDeclarative -I../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -Isrc -Iqmlapplicationviewer -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -LC:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -lz -lQtDeclarative -lQtDBus -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = c:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		src/json.cpp \
		src/pbwire.cpp \
		src/signutil.cpp \
		src/clientinfo.cpp \
		src/httpclient.cpp \
		src/db.cpp \
		src/accountmanager.cpp \
		src/appsettings.cpp \
		src/thememanager.cpp \
		src/imagecache.cpp \
		src/notifier.cpp \
		src/util.cpp \
		src/content.cpp \
		src/proto_messages.cpp \
		src/tiebaapi.cpp \
		src/logstore.cpp \
		src/qrlogin.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc/moc_clientinfo.cpp \
		moc/moc_httpclient.cpp \
		moc/moc_db.cpp \
		moc/moc_accountmanager.cpp \
		moc/moc_appsettings.cpp \
		moc/moc_thememanager.cpp \
		moc/moc_imagecache.cpp \
		moc/moc_notifier.cpp \
		moc/moc_util.cpp \
		moc/moc_tiebaapi.cpp \
		moc/moc_logstore.cpp \
		moc/moc_qrlogin.cpp \
		moc/moc_qmlapplicationviewer.cpp
OBJECTS       = obj/main.o \
		obj/json.o \
		obj/pbwire.o \
		obj/signutil.o \
		obj/clientinfo.o \
		obj/httpclient.o \
		obj/db.o \
		obj/accountmanager.o \
		obj/appsettings.o \
		obj/thememanager.o \
		obj/imagecache.o \
		obj/notifier.o \
		obj/util.o \
		obj/content.o \
		obj/proto_messages.o \
		obj/tiebaapi.o \
		obj/logstore.o \
		obj/qrlogin.o \
		obj/qmlapplicationviewer.o \
		obj/moc_clientinfo.o \
		obj/moc_httpclient.o \
		obj/moc_db.o \
		obj/moc_accountmanager.o \
		obj/moc_appsettings.o \
		obj/moc_thememanager.o \
		obj/moc_imagecache.o \
		obj/moc_notifier.o \
		obj/moc_util.o \
		obj/moc_tiebaapi.o \
		obj/moc_logstore.o \
		obj/moc_qrlogin.o \
		obj/moc_qmlapplicationviewer.o
DIST          = ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		tieba.pro
QMAKE_TARGET  = tieba
DESTDIR       = 
TARGET        = tieba

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): i18n/tieba_zh_CN.qm i18n/tieba_zh_TW.qm i18n/tieba_ja.qm i18n/tieba_ko.qm i18n/tieba_en.qm $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tieba.pro  ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDBus.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile tieba.pro
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDBus.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile tieba.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/tieba1.0.0 || $(MKDIR) obj/tieba1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/tieba1.0.0/ && $(COPY_FILE) --parents i18n\tieba_zh_CN.ts i18n\tieba_zh_TW.ts i18n\tieba_ja.ts i18n\tieba_ko.ts i18n\tieba_en.ts obj/tieba1.0.0/ && $(COPY_FILE) --parents src/json.h src/pbwire.h src/signutil.h src/clientinfo.h src/httpclient.h src/db.h src/accountmanager.h src/appsettings.h src/thememanager.h src/imagecache.h src/notifier.h src/util.h src/content.h src/proto_messages.h src/tiebaapi.h src/logstore.h src/qrlogin.h qmlapplicationviewer/qmlapplicationviewer.h obj/tieba1.0.0/ && $(COPY_FILE) --parents main.cpp src/json.cpp src/pbwire.cpp src/signutil.cpp src/clientinfo.cpp src/httpclient.cpp src/db.cpp src/accountmanager.cpp src/appsettings.cpp src/thememanager.cpp src/imagecache.cpp src/notifier.cpp src/util.cpp src/content.cpp src/proto_messages.cpp src/tiebaapi.cpp src/logstore.cpp src/qrlogin.cpp qmlapplicationviewer/qmlapplicationviewer.cpp obj/tieba1.0.0/ && $(COPY_FILE) --parents i18n\tieba_zh_CN.ts i18n\tieba_zh_TW.ts i18n\tieba_ja.ts i18n\tieba_ko.ts i18n\tieba_en.ts obj/tieba1.0.0/ && (cd `dirname obj/tieba1.0.0` && $(TAR) tieba1.0.0.tar tieba1.0.0 && $(COMPRESS) tieba1.0.0.tar) && $(MOVE) `dirname obj/tieba1.0.0`/tieba1.0.0.tar.gz . && $(DEL_FILE) -r obj/tieba1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_ts2qm_make_all: i18n/tieba_zh_CN.qm i18n/tieba_zh_TW.qm i18n/tieba_ja.qm i18n/tieba_ko.qm i18n/tieba_en.qm
compiler_ts2qm_clean:
	-$(DEL_FILE) i18n/tieba_zh_CN.qm i18n/tieba_zh_TW.qm i18n/tieba_ja.qm i18n/tieba_ko.qm i18n/tieba_en.qm
i18n/tieba_zh_CN.qm: i18n/tieba_zh_CN.ts
	c:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/lrelease i18n/tieba_zh_CN.ts -qm i18n/tieba_zh_CN.qm

i18n/tieba_zh_TW.qm: i18n/tieba_zh_TW.ts
	c:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/lrelease i18n/tieba_zh_TW.ts -qm i18n/tieba_zh_TW.qm

i18n/tieba_ja.qm: i18n/tieba_ja.ts
	c:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/lrelease i18n/tieba_ja.ts -qm i18n/tieba_ja.qm

i18n/tieba_ko.qm: i18n/tieba_ko.ts
	c:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/lrelease i18n/tieba_ko.ts -qm i18n/tieba_ko.qm

i18n/tieba_en.qm: i18n/tieba_en.ts
	c:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/lrelease i18n/tieba_en.ts -qm i18n/tieba_en.qm

compiler_moc_header_make_all: moc/moc_clientinfo.cpp moc/moc_httpclient.cpp moc/moc_db.cpp moc/moc_accountmanager.cpp moc/moc_appsettings.cpp moc/moc_thememanager.cpp moc/moc_imagecache.cpp moc/moc_notifier.cpp moc/moc_util.cpp moc/moc_tiebaapi.cpp moc/moc_logstore.cpp moc/moc_qrlogin.cpp moc/moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_clientinfo.cpp moc/moc_httpclient.cpp moc/moc_db.cpp moc/moc_accountmanager.cpp moc/moc_appsettings.cpp moc/moc_thememanager.cpp moc/moc_imagecache.cpp moc/moc_notifier.cpp moc/moc_util.cpp moc/moc_tiebaapi.cpp moc/moc_logstore.cpp moc/moc_qrlogin.cpp moc/moc_qmlapplicationviewer.cpp
moc/moc_clientinfo.cpp: src/clientinfo.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/clientinfo.h -o moc/moc_clientinfo.cpp

moc/moc_httpclient.cpp: src/httpclient.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/httpclient.h -o moc/moc_httpclient.cpp

moc/moc_db.cpp: src/db.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/db.h -o moc/moc_db.cpp

moc/moc_accountmanager.cpp: src/accountmanager.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/accountmanager.h -o moc/moc_accountmanager.cpp

moc/moc_appsettings.cpp: src/appsettings.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/appsettings.h -o moc/moc_appsettings.cpp

moc/moc_thememanager.cpp: src/thememanager.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/thememanager.h -o moc/moc_thememanager.cpp

moc/moc_imagecache.cpp: src/httpclient.h \
		src/imagecache.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/imagecache.h -o moc/moc_imagecache.cpp

moc/moc_notifier.cpp: src/notifier.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/notifier.h -o moc/moc_notifier.cpp

moc/moc_util.cpp: src/util.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/util.h -o moc/moc_util.cpp

moc/moc_tiebaapi.cpp: src/httpclient.h \
		src/signutil.h \
		src/tiebaapi.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/tiebaapi.h -o moc/moc_tiebaapi.cpp

moc/moc_logstore.cpp: src/logstore.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/logstore.h -o moc/moc_logstore.cpp

moc/moc_qrlogin.cpp: src/qrlogin.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/qrlogin.h -o moc/moc_qrlogin.cpp

moc/moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc/moc_qmlapplicationviewer.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_ts2qm_clean compiler_moc_header_clean 

####### Compile

obj/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/json.o: src/json.cpp src/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/json.o src/json.cpp

obj/pbwire.o: src/pbwire.cpp src/pbwire.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pbwire.o src/pbwire.cpp

obj/signutil.o: src/signutil.cpp src/signutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/signutil.o src/signutil.cpp

obj/clientinfo.o: src/clientinfo.cpp src/clientinfo.h \
		src/signutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/clientinfo.o src/clientinfo.cpp

obj/httpclient.o: src/httpclient.cpp src/httpclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/httpclient.o src/httpclient.cpp

obj/db.o: src/db.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/db.o src/db.cpp

obj/accountmanager.o: src/accountmanager.cpp src/accountmanager.h \
		src/db.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/accountmanager.o src/accountmanager.cpp

obj/appsettings.o: src/appsettings.cpp src/appsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/appsettings.o src/appsettings.cpp

obj/thememanager.o: src/thememanager.cpp src/thememanager.h \
		src/appsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/thememanager.o src/thememanager.cpp

obj/imagecache.o: src/imagecache.cpp src/imagecache.h \
		src/httpclient.h \
		src/signutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/imagecache.o src/imagecache.cpp

obj/notifier.o: src/notifier.cpp src/notifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/notifier.o src/notifier.cpp

obj/util.o: src/util.cpp src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/util.o src/util.cpp

obj/content.o: src/content.cpp src/content.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/content.o src/content.cpp

obj/proto_messages.o: src/proto_messages.cpp src/proto_messages.h \
		src/pbwire.h \
		src/content.h \
		src/clientinfo.h \
		src/accountmanager.h \
		src/signutil.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/proto_messages.o src/proto_messages.cpp

obj/tiebaapi.o: src/tiebaapi.cpp src/tiebaapi.h \
		src/httpclient.h \
		src/signutil.h \
		src/json.h \
		src/proto_messages.h \
		src/clientinfo.h \
		src/accountmanager.h \
		src/appsettings.h \
		src/content.h \
		src/db.h \
		src/logstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tiebaapi.o src/tiebaapi.cpp

obj/logstore.o: src/logstore.cpp src/logstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/logstore.o src/logstore.cpp

obj/qrlogin.o: src/qrlogin.cpp src/qrlogin.h \
		src/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrlogin.o src/qrlogin.cpp

obj/qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

obj/moc_clientinfo.o: moc/moc_clientinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_clientinfo.o moc/moc_clientinfo.cpp

obj/moc_httpclient.o: moc/moc_httpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_httpclient.o moc/moc_httpclient.cpp

obj/moc_db.o: moc/moc_db.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_db.o moc/moc_db.cpp

obj/moc_accountmanager.o: moc/moc_accountmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_accountmanager.o moc/moc_accountmanager.cpp

obj/moc_appsettings.o: moc/moc_appsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_appsettings.o moc/moc_appsettings.cpp

obj/moc_thememanager.o: moc/moc_thememanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_thememanager.o moc/moc_thememanager.cpp

obj/moc_imagecache.o: moc/moc_imagecache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_imagecache.o moc/moc_imagecache.cpp

obj/moc_notifier.o: moc/moc_notifier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_notifier.o moc/moc_notifier.cpp

obj/moc_util.o: moc/moc_util.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_util.o moc/moc_util.cpp

obj/moc_tiebaapi.o: moc/moc_tiebaapi.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tiebaapi.o moc/moc_tiebaapi.cpp

obj/moc_logstore.o: moc/moc_logstore.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_logstore.o moc/moc_logstore.cpp

obj/moc_qrlogin.o: moc/moc_qrlogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qrlogin.o moc/moc_qrlogin.cpp

obj/moc_qmlapplicationviewer.o: moc/moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qmlapplicationviewer.o moc/moc_qmlapplicationviewer.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/tieba/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/tieba/qml/ 
	-$(INSTALL_DIR) c:/Users/ae/Desktop/tieba/qml/tieba $(INSTALL_ROOT)/opt/tieba/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/tieba/qml/tieba
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/tieba/qml/ 


install_itemfolder_02: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/tieba/./ || $(MKDIR) $(INSTALL_ROOT)/opt/tieba/./ 
	-$(INSTALL_DIR) c:/Users/ae/Desktop/tieba/i18n $(INSTALL_ROOT)/opt/tieba/./


uninstall_itemfolder_02:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/tieba/./i18n
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/tieba/./ 


install_itemfolder_03: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/tieba/./ || $(MKDIR) $(INSTALL_ROOT)/opt/tieba/./ 
	-$(INSTALL_DIR) c:/Users/ae/Desktop/tieba/fonts $(INSTALL_ROOT)/opt/tieba/./


uninstall_itemfolder_03:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/tieba/./fonts
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/tieba/./ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) c:/Users/ae/Desktop/tieba/tieba80.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/tieba80.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) c:/Users/ae/Desktop/tieba/tieba_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/tieba_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/tieba/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/tieba/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/tieba/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/tieba/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/tieba/bin/ 


install:  install_itemfolder_01 install_itemfolder_02 install_itemfolder_03 install_icon install_desktopfile install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_itemfolder_02 uninstall_itemfolder_03 uninstall_icon uninstall_desktopfile uninstall_target   FORCE

FORCE:

