import QtQuick 1.1

// Theme-aware monochrome SVG icon. Icon set lives in qml/tieba/icons and is
// generated by tools/gen-icons.ps1 (light + dark variants).
Image {
    id: root
    property string name: ""
    property bool dark: appTheme.dark
    source: name === "" ? "" :
            Qt.resolvedUrl("../icons/" + (dark ? "dark" : "light") + "/" + name + ".svg")
    sourceSize.width: 48
    sourceSize.height: 48
    smooth: true
    asynchronous: true
}
